### PR TITLE
Add react-combobox

### PR DESCRIPTION
**Pull request by jmfury**
🎟️ [Asana Task](https://app.asana.com/0/1200392284811676/1200454406603165/f)
🔍 [Preview Link](https://react-components-git-jmadd-react-combobox-hashicorp.vercel.app/components/combobox)

---

## Description

This PR adds a new 📦 for `<Combobox />` 

### Background

While `<SelectInput />` does leverage Downshift as a dependency it is not currently meant to support a basic _Combobox_ use case where the user should be able to do the following...

#### Features
- Type into an `<input />`
- Receive typeahead or autocomplete suggestions in a dropdown below
- Select an option to update said `<input />`
- Get sensible browsing, selection, and reset interactions via keyboard and click interactions
- ... etc.

### Why add this?
One such use case came up recently where @kendallstrautman [created a `<Combobox />` from scratch 👩‍🍳](https://github.com/hashicorp/hashicorp-www-next/tree/main/components/_page-components/start/start-form/fields/country-combo-box) - see [_Country_ field here 🌐 ](https://www.hashicorp.com/request-pricing)

This is objectively an awesome component and contains solid reusable components within. That said, we would argue that the next dev should probably not have to build something similar for their use case 🧑‍🤝‍🧑 

### Goals for this component's API
- Provide the required functionality (see Features above)
- Accessibility first
- Endorse composition, don't prescribe implementation details
- Do provide baseline, styled elements which consumers may still customers or work around entirely if they so choose.

## Release Information

Please select one (**required**)

- [ ] **Major** (This PR introduces a breaking (incompatible API) change)
- [ ] **Minor** (This PR adds functionality but it backwards-compatible)
- [X] **Patch** (This PR adds a backwards-compatible bug fix)

<details>
<summary>Release Notes (<strong>required</strong>)</summary>

</details>

---

### PR Checklist 🚀

Items in this checklist may not may not apply to your PR, but please consider each item carefully.

- [ ] Add Asana and Preview links above.
- [ ] Conduct thorough self-review.
- [ ] Add or update tests as appropriate.
- [ ] Write a useful description (above) to give reviewers appropriate context.
- [ ] Add release notes to the appropriate section (above).
- [ ] Conduct reasonable cross browser testing for both compatibility and responsive behavior (We have a [Cross Browser Testing](https://crossbrowsertesting.com) account for this, if you don't have access, just ask!).
- [ ] Conduct reasonable accessibility review (use the [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) as a guide or an [axe browser plugin](https://www.deque.com/axe/) until we establish more formal checks).
- [ ] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

### CODE REVIEW

**Comment by jmfury** [comment]
@BRKalow  I am going to rebase this (noting the conflict). 👀  appreciated - no rush of course!

[Just had a ticket come up ](https://app.asana.com/0/346384260719996/1200468245445243)where this component might be a nice win on Dotcom so reviving the effort if I can here!

**Comment by BRKalow** [comment]
@jmfury I can't proceed past the first option using the down arrow in the batteries included or formik examples 🤔

**Comment by jmfury** [comment]
> @jmfury I can't proceed past the first option using the down arrow in the batteries included or formik examples 🤔

@BRKalow 
Oh wow! Great catch, thanks so much! 

The implementations of `renderOption` in the Swingset page were stale.. Updating!

**Comment by jmfury** [comment]
@BRKalow  - Fresh rebase here, should be good to go 🎩

**Review by BRKalow — APPROVED** [review]
👏

**Pull request merged**
