### PR TITLE
Chore: Bump `mktg-logos` to v1.3.2

### PR DESCRIPTION
**Pull request by nandereck**
🎟️ [Asana Task](https://app.asana.com/0/1202791227659279/1203093711604797/f)
🔍 [Preview Link](https://react-components-git-nels-choresbump-mktg-logos-hashicorp.vercel.app/components/subnav)

---

## Description
It was recently discovered that the old Vault logo is currently being used in the `Subnav` component. This PR updates packages so as to use the new logos (logo change [here](https://github.com/hashicorp/mktg-logos/pull/9)).

## Validation Steps
- Navigate to the [`Subnav` in Preview](https://react-components-git-nels-choresbump-mktg-logos-hashicorp.vercel.app/components/subnav)
- Set `text` in the `titleLink` prop to `HashiCorp Vault`
- Verify that the correct logo is displayed:
Screen Shot 2022-10-04 at 9 31 16 AM

### PR Checklist 🚀

Items in this checklist may not may not apply to your PR, but please consider each item carefully.

- [x] Add Asana and Preview links above.
- [x] Conduct thorough self-review.
- [ ] Add or update tests as appropriate.
- [ ] Conduct reasonable cross browser testing for both compatibility and responsive behavior (We have a [Sauce Labs](https://app.saucelabs.com/) account for this, if you don't have access, just ask!).
- [ ] Conduct reasonable accessibility review (use the [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) as a guide or an [axe browser plugin](https://www.deque.com/axe/) until we establish more formal checks).
- [ ] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

### CODE REVIEW

**Review by alexcarpenter — COMMENTED** [review]
LGTM. Do you wan to test a canary release to 100% verify in dev portal before merging here?

**Comment by nandereck** [comment]
> LGTM. Do you wan to test a canary release to 100% verify in dev portal before merging here?

Wasn't sure how best to test on dev portal. I'll do that. Thanks!

**Comment by nandereck** [comment]
@alexcarpenter - confirmed this does the trick. Mind giving this one more look?

**Review by alexcarpenter — APPROVED** [review]
Might need an `npm i` to fix the package-lock.json conflict, but approving!

**Pull request merged**
