### PR TITLE
DocsSidenav - add headline option

### PR DESCRIPTION
**Pull request by jescalan**
🔍 [Preview Link](https://react-components-e8inu5aoi-hashicorp.vercel.app/components/docssidenav)

---

## Description

We need the capability to add small headlines to the sidenav for Terraform, this is a nice simple implementation of it.

### PR Checklist 🚀

Items in this checklist may not may not apply to your PR, but please consider each item carefully.

- [ ] Add Asana and Preview links above.
- [ ] Conduct thorough self-review.
- [ ] Add or update tests as appropriate.
- [ ] Conduct reasonable cross browser testing for both compatibility and responsive behavior (We have a [Sauce Labs](https://app.saucelabs.com/) account for this, if you don't have access, just ask!).
- [ ] Conduct reasonable accessibility review (use the [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) as a guide or an [axe browser plugin](https://www.deque.com/axe/) until we establish more formal checks).
- [ ] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

### CODE REVIEW

**Review by BRKalow — CHANGES_REQUESTED** [review]
Can we also update the `types.ts` file with the new heading node type?

https://github.com/hashicorp/react-components/blob/main/packages/docs-sidenav/types.ts

**Review by EnMod — CHANGES_REQUESTED** [review]
Code looks good, nice and simple :+1: 

It seems that the search filter is now broken though, entering in any value throws this error:

`TypeError: Cannot read property 'toLowerCase' of undefined`

The `filterContent` util function seems to be the culprit, specifically this check at [line 11](https://github.com/hashicorp/react-components/blob/main/packages/docs-sidenav/utils/filter-content.js#L11):

```javascript
const isTitleMatch = fuzzysearch(
  searchValue.toLowerCase(),
  item.title.toLowerCase()
)
```

I'm thinking now it needs to account for the possibility of headings?

**Review by BRKalow — APPROVED** [review]
👍  nice!

**Review by EnMod — APPROVED** [review]
Cool, LGTM!

**Pull request merged**
