### PR TITLE
fix: dismiss overflow dropdown on anchor click

### PR DESCRIPTION
**Pull request by dstaley**
🎟️ [Asana Task](https://app.asana.com/0/0/1201476871035773/f)
🔍 [Preview Link](https://react-components-git-{branch-slug}-hashicorp.vercel.app)

---

## Description

This extends the behavior added in https://github.com/hashicorp/react-components/pull/426 to the MenuItemsOverflow component, which is used on mobile devices.

### PR Checklist 🚀

Items in this checklist may not may not apply to your PR, but please consider each item carefully.

- [x] Add Asana and Preview links above.
- [x] Conduct thorough self-review.
- [x] Add or update tests as appropriate.
- [x] Conduct reasonable cross browser testing for both compatibility and responsive behavior (We have a [Sauce Labs](https://app.saucelabs.com/) account for this, if you don't have access, just ask!).
- [x] Conduct reasonable accessibility review (use the [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) as a guide or an [axe browser plugin](https://www.deque.com/axe/) until we establish more formal checks).
- [x] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

### CODE REVIEW

**Review by alexcarpenter — APPROVED** [review]
👍🏼

**Comment by alexcarpenter** [comment]
@dstaley I think I found a bug where menus are not closing on click. In the use case that we pass a `next/link` to the link prop in subnav. `event.target.tagName` is not equal to `'A'`?

```jsx
import Link from 'next/link'

<Subnav Link={Link} />
```

**Comment by dstaley** [comment]
Hmm, I'm not seeing that behavior on the [terraform-website-next site](https://github.com/hashicorp/terraform-website-next/blob/asm.nq.migration-tasks/pages/_app.js#L57).

It might be a better idea for us to use a router hook and listen for navigation events rather than detecting clicks.

**Comment by alexcarpenter** [comment]
@dstaley Check out this preview here https://cloud-hashicorp-com-msy3mvgid-hashicorp.vercel.app/products/vault

Toggle between products in the primary nav.

**Pull request merged**
