### PR TITLE
fix: center inline-video description

### PR DESCRIPTION
**Pull request by LeahMarieBush**
🎟️ [Asana Task](https://app.asana.com/0/1208185803237298/1206900259194096/f)
🔍 [Preview Link](https://react-components-git-leah-fixcenter-video-description-hashicorp.vercel.app/components/inlinevideo)

---

## Description

This PR centers the description below the video for inline-videos. This came in as a request from the Web Presence Request form. More info on why is in the Asana task.

To fix this, I added `text-align: center` to the video description.

## Testing
1. Go to preview link
2. At the top, note that the descriptions below the videos are centered

### PR Checklist 🚀

Items in this checklist may not may not apply to your PR, but please consider each item carefully.

- [x] Add Asana and Preview links above.
- [x] Conduct thorough self-review.
- [x] Add or update tests as appropriate.
- [x] Conduct reasonable cross browser testing for both compatibility and responsive behavior (We have a [Sauce Labs](https://app.saucelabs.com/) account for this, if you don't have access, just ask!).
- [x] Conduct reasonable accessibility review (use the [WAS](https://accessible.org/Web-Accessibility-Standards-WAS-2.pdf) as a guide or an [axe browser plugin](https://www.deque.com/axe/) until we establish more formal checks).
- [x] Identify (in the description above) and document (add Asana tasks on [this board](https://app.asana.com/0/1100423001970639/list)) any technical debt that you're aware of, but are not addressing as part of this PR.

### CODE REVIEW

**Comment by nandereck** [comment]
@LeahMarieBush - what's the reason for the `package-lock.json` change?

**Review by nandereck — APPROVED** [review]
One question about the change to `package-lock.json`. Otherwise, LGTM!

**Comment by LeahMarieBush** [comment]
> @LeahMarieBush - what's the reason for the `package-lock.json` change?

I ran `npm i` after creating the branch and it updated the `package-lock.json` file. I looked at the updated versions and they are all accurate with the current versions of each updated package. I would guess that the packages got updated but there was no corresponding `npm i` command run, probably because the bot updates the packages after each PR is merged

**Comment by nandereck** [comment]
> > @LeahMarieBush - what's the reason for the `package-lock.json` change?
> 
> @nandereck I ran `npm i` after creating the branch and it updated the `package-lock.json` file. I looked at the updated versions and they are all accurate with the current versions of each updated package. I would guess that the packages got updated but there was no corresponding `npm i` command run, probably because the bot updates the packages after each PR is merged

Cool SG!

**Pull request merged**
